# Usa la imagen oficial de Go 1.23.0 para desarrollo
FROM golang:1.23.0-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Instala las dependencias necesarias
RUN apk add --no-cache git

# Descarga e instala Air para recarga automática
RUN go install github.com/air-verse/air@latest

# Copia los archivos necesarios para instalar dependencias
COPY go.mod go.sum ./
RUN go mod download

# Copia todo el código fuente
COPY . .

# Expone el puerto de la API
EXPOSE 8080

# Comando para iniciar Air y recargar automáticamente
CMD ["air"]
