version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Usa Dockerfile.prod para producción
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
    profiles:
      - dev
      - prod
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles:
      - prod
      - dev

volumes:
  dbdata:
    name: prod-dbdata
